theme: cotes2020/jekyll-theme-chirpy
title: "Justin Rohde — Portfolio"
description: "Portfolio of Justin Rohde — cybersecurity engineering student, red teaming enthusiast, builder of systems & tools."
url: "https://jrohde23.github.io"
baseurl: ""
lang: "en"
